cerner/clara-rules

src/main/clojure/clara/rules.clj, src/main/clojure/clara/rules/engine.clj, src/test/clojure/clara/test_rules.clj
Found a similar issue to what I discovered in both https://github.com/rbrush/clara-rules/pull/59 and https://github.com/rbrush/clara-rules/pull/74.
There is another use of `concat` that is subject to StackOverflowError.  This time it is in the `clara.rules.engine` namespace.  Previously I was only focusing in on the `clara.rules.memory` namespace for issues like this to fix.
I have fixed it the same way that I fixed the previous pull requests listed here.  I have changed the usage of the lazily evaluated `concat` to eagerly evaluated `into`.  Again I do not believe there are any unwanted side effects for going from lazy to eager in this scenario.
In `clara.rules.engine` the special accumulate node type `AccumulateWithJoinFilterNode` had a use of `concat` in the `right-activate-reduced` …
=> Fix potential StackOverflowError retracting previous accumulated items

src/main/clojure/clara/rules/engine.clj, src/main/clojure/clara/rules/memory.clj, src/main/clojurescript/clara/rules/memory.cljs, src/test/clojure/clara/test_rules.clj
This is a pull request to deal with what was discussed @ https://github.com/rbrush/clara-rules/issues/78.
- Put together a few test cases showing where previously reduced accumulations that return nil cause retractions of tokens to be missed
- Fixing this centers around disambiguating the cases of no-accum-reduced-ever vs nil-accum-reduced-value when calling clara.rules.memory/get-accum-reduced fn
- Added test case for both AccumulateNode and AccumulateWithJoinFilterNode to verify the issue is fixed
=> Token retractions may not occur when an accumulator reduces to nil

src/main/clojure/clara/rules/engine.clj, src/main/clojure/clara/rules/memory.clj, src/main/clojurescript/clara/rules/memory.cljs, src/test/clojure/clara/test_rules.clj
This is a follow up to the issue discussed at https://github.com/rbrush/clara-rules/issues/84.  Facts in working memory with equal values had a potential
to not be properly retracted due to sets being used to group together facts to retract.
The biggest changes here are to the `clara.rules.memory/remove-first-of-each` function.  The former set of items to remove is now an arbitrary seq instead to account for duplicates.
The changes are a bit verbose in order to preserve the efficiency of this function via low-level looping and the use of transients.
----
I noted a few points to consider:
--
(1)
The most common usage of this function is in clara.rules.memory itself and it has the form:
```clj
filtered-elements (remove-first-of-each elements previous-elements)
```
Followed shortly by logic …
=> Proper truth maintenance when retracting equal facts

src/main/clojure/clara/rules/engine.clj, src/test/clojure/clara/test_rules.clj
I have added a test to clara.test-rules that reveals an issue with how NegationNodes maintain their node memory for retracted tokens in the `left-retract` impl within clara.rules.engine ns.
Basically, when tokens were given to a NegationNode on `left-retract` they were not removed from the nodes memory.  If at a later point a `right-retract` happened for the same NegationNode it could result in tokens being propagated that should have been retracted and removed from the node's memory earlier.
I have added a test to clara.test-rules to show this issue.  It is difficult to demonstrate with a simplified example, so I just used the clara.rules.testfacts First, Second, Third, and Fourth to demonstrate a scenario that would fail.
In this test case, notice that different rule saliences would …
=> NegationNode should delete removed tokens from node memory on left-retract

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/dsl.clj, src/main/clojure/clara/rules/engine.clj, src/test/clojure/clara/test_rules.clj
As demonstrated in the test case added here to clara.test-rules, variable bindings in rules are overlooked by the rule DSL parsing and rule compilation if the
variables appear in non-sequential Clojure literals.  This would result in compilation errors.
--
The root cause of this issue is the use of  `clojure.core/flatten`.  `flatten` does not behave as often would be expected on non-sequential forms.
A simple demonstration:
```clj
(flatten [1 [2] #{4 [5]} {:a 6}])
;= (1 2 #{4 [5]} {:a 6})
;; Or more simple
(flatten [#{1 2 3}])
;= (#{1 3 2})
;; Or even (arguably) weird
(flatten #{1 2 3})
;= ()
```
I know I've seen people surprised by this in online posts floating around.  If I were to guess why `flatten` behaves the way it does on non-sequentials, it would be
due to the fact that Clojure …
=> Allow binding variables to be used in non-sequential literals

src/main/clojurescript/clara/macros.clj, src/test/clojurescript/clara/test_rules.cljs, src/test/clojurescript/clara/test_rules_data.clj
Formerly, Clara/cljs could only load productions from a namespace. This
commit allows `defsession` to take an arbitrary expression, which is
evaluated *in clojure*, and may return a collection of productions that
will be used.
This can be useful in one of two modes:
- As part of a normal CLJS build process using (e.g.) lein-cljsbuild,
rules can now be read from (for example) data files instead of
ClojureScript source files.
- It is possible to set up a server which can compile and serve up new
rule-containing JavaScript files *on demand*, generating sets of rules
dynamically from (for example) a database.
=> Allow explicitly specifying productions in CLJS

src/main/clojurescript/clara/rules.cljs
It wasn't there for some reason; now it is.
=> Support insert-all! in CLJS

src/main/clojure/clara/rules/compiler.clj, src/test/clojure/clara/test_rules.clj
I noticed a difference in the rete network made when using a qualified vs unqualified `=` or `==` in rules for fact bindings.  This was due the clara.rules.compiler only searching for the unqualified variety.
This came up due to generating rules via a macro and using the syntax-quote, which auto-qualifies symbols.  I think this may be a common thing that would be done, so I'm offering this PR to fix the issue.
The solution is to just resolve symbols to vars when possible, then see if they are clojure.core/= or == regardless of being qualified, aliased, or unqualified.
The assumption is that `clojure.core/=` and `==` are the symbols that clara intends to be used for fact bindings.
It would be an interesting case if someone had a definition of their own `=` or `==` in their namespace …
=> Qualified/aliased/unqualified clojure.core = or == should produce the same rete network

src/main/clojure/clara/rules.clj, src/main/clojure/clara/rules/dsl.clj, src/test/clojure/clara/test_rules.clj
clara.rules.dsl mistakenly treats the `..` macro symbol as a Java/host constructor call, which causes a NPE to throw.
- Adding a special case to avoid the `..` macro symbol in the constructor call conditional
=> Clara DSL throws NPE for `..` macro symbol

src/main/clojure/clara/rules/compiler.clj, src/test/clojure/clara/test_rules.clj
- Comparing arbitrary conditions in clara.rules.compiler (i.e. `gen-compare`) has potentially to throw NPE.  Implemented handling and reproduction case.
=> Ensure compiler condition comparison nil-safe

src/main/clojure/clara/rules/compiler.clj
Fix for issue 113: Aliased symbols not resolved in cljs.
=> Keys in the :requires map of ns-info are symbols.

src/main/clojurescript/clara/rules.cljs
The ancestors-fn option isn't handled on clojurescript side.
The fix is very simple changes to create-get-alphas-fn and assemble-session as far as I can see.
PR to follow.
=> Ancestors-fn support for clojurescript

src/main/clojure/clara/rules/dsl.clj, src/test/clojure/clara/test_rules.clj, src/test/clojurescript/clara/test_rules.cljs
=> RHS captures all s-expressions using implicit `do`

src/main/clojure/clara/rules/schema.clj, src/test/clojure/clara/test_rules.clj
When generating Clara rules a case was encountered where the s-expression predication of `list?` was too restrictive in clara.rules.schema.  This patch generalizes it to `seq?` to allow to accept forms such as a clojure.lang.Cons which can easily creep up in code forms generated with syntax quote in Clojure.
e.g.
```clj
(type `(= 1 2))
;= clojure.lang.Cons
(list? `(= 1 2))
;= false
(seq? `(= 1 2))
;= true
```
=> More general clara.rules.schema for s-expression forms

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/testfacts.clj, src/test/clojure/clara/test_rules.clj
Clojure symbols are more flexible than those allowed by Java in many cases.  For Clojure records, this applies to Java field names.  The Clojure compiler automatically applies a process referred to as "munging" in order to convert flexible Clojure symbols to valid Java field names.
Clara should support reference to field names on Clojure records despite if they are munged on the underlying Java class or not.
The approach taken here was to overhaul the clara.rules.compile/get-field-accessors function that is used specifically for clojure.lang.IRecord subclasses.  Clojure IRecord impls have, for quite a few releases, had a static method that was introduced for "tooling" called `getBasis` [1].  This returns the "unmunged" field names of the Clojure record ordered consistent with the original …
=> Allow "munged" Clojure record field names to be used directly in rules

src/test/clojure/clara/test_rules.clj
When doing https://github.com/rbrush/clara-rules/pull/121 I wrote a test that mistakenly didn't test what it was supposed to.  This just fixes that test to correctly run the assertion it was intended to.
The enhancement to allow "munged" field names to be used directly in rules still works as expected.
=> Small test fix for munged field names

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/dsl.clj, src/test/clojure/clara/test_rules.clj
In `clara.rules.compiler/non-equality-unification?` the criteria to find complex non-equality unifications is too restrictive and can miss "complex" unifications.  The issue is that `list?` is used which specifically only works for clojure.lang.IPersistentList impl's.  Often enough, Clojure s-expressions are other data types that are not covered by `list?`.  It seems that the safest bet for this sort of test is to stick with `seq?`.  This doesn't come up necessarily when rules are created via the Clara DSL macros and functions, however, if other methods of rule generation are used, this is likely to happen.
I have added a test demonstrating how this compiler issue could cause what seems to be valid rules to not compile.  I have also changed the other occurrence of `list?` I found in an …
=> Use seq? instead of list? when looking for non-equality unifications

src/main/clojure/clara/rules.cljc, src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/rules/memory.cljc
I was looking at performance across a few fairly large rulebases and large dataset I had to work with.  While profiling, I noticed a few easy to spot performance time sinks coming out of the reflection warnings in clara.rules.memory.  I also saw a few places where using `clara.rules.platform/tuned-group-by` would be preferable than Clojure's built-in `group-by`.
=> Performance enhancements

src/main/clojure/clara/rules/engine.cljc
I have identified what looks like a quick and easy performance optimization for Clara accumulator node retraction logic.
As implemented, I think that `clara.rules.engine/right-retract`s are not retracting facts in a batch/collection-based style.  This is in contrast to how the `c.r.e/right-activate` does perform accumulation logic in batches.
I'd like to have stronger benchmarks for some future changes, but I think for this one I can make a pretty brute-force example to demonstrate the speed to be gained.
Before change:
```clj
(let [r1 (dsl/parse-rule [[?ts <- (acc/all) :from [Temperature]]]
(insert! (->TemperatureHistory ?ts)))
r2 (dsl/parse-rule [[TemperatureHistory (= ?ts temperatures)]]
(insert-all! (map (comp ->Cold :temperature) ?ts)))
q (dsl/parse-query []
[[?cs <- (acc/all) :from …
```
=> Batch right-retracts in accumulate nodes

src/main/clojure/clara/rules/compiler.clj
I have noticed some new reflection warnings creeping up from the work done with https://github.com/rbrush/clara-rules/issues/149 where `clara.rules.compiler/extract-negations` was added.
The issue is that Clara rules conditions schema for clara.rules.schema.FactType `:type` is open to be more than just Class instances https://github.com/rbrush/clara-rules/blob/0.9.2/src/main/clojure/clara/rules/schema.clj#L29 .  The compiler appropriately allows the type of `:type` to not be important.  However, when the type is a Class instance, it is used as `:tag` metadata so that Clojure doesn't need to do reflection when accessing fields of objects in rule conditions.
When `extract-negations` was added, it used a Symbol rather than a Class for the `:type` of the condition.  This could just be …
=> Remove potential reflection

src/main/clojure/clara/rules/compiler.clj, src/test/clojure/clara/test_rules.clj
A few error messages I have seen during testing newer changes in the current snapshot have lost one part of the changes from https://github.com/rbrush/clara-rules/pull/156.
The `:production` is not showing up when `clara.rules.compiler/try-eval` fails like it was intended to.  This was lost in the clara.rules.compiler rework done with https://github.com/rbrush/clara-rules/commit/f9537c7540e1a8baa5cf07f0f88b0116125d31f9.
I have added it back again and added a few tests to attempt to validate that this isn't overlooked again in the future as easily.
=> providing compile context during compilation (take 2)

src/main/clojure/clara/rules/accumulators.cljc, src/test/clojure/clara/test_accumulators.clj
This PR adds a `grouping-by` accumulator.
Basic example:
```clojure
(defrecord Foo [num])
(def grouping-accum (clara.rules.accumulators/grouping-by :num))
(defquery q:grouped-foos []
[?grouped-foos <- grouping-accum :from [Foo]])
(-> (mk-session [q:grouped-foos])
(insert-all [(->Foo 1)
(->Foo 2)
(->Foo 3)])
(query q:grouped-foos))
;; ({:?grouped-foos {1 [#clara.rules.testfacts.Foo{:num 1}], 2 [#clara.rules.testfacts.Foo{:num 2}], 3 [#clara.rules.testfacts.Foo{:num 3}]}})
```
An example of using the optional `convert-return-fn` argument:
```clojure
(defrecord Foo [num])
(defn max-foos
[m]
(if (seq m)
(->> (keys m)
(map #(Long/parseLong %))
(apply max)
(str)
(get m))
m))
(def grouping-accum (clara.rules.accumulators/grouping-by :num max-foos))
(defquery q:max-foos []
[?max-foos <- …
```
=> Add grouping-by accumulator

.gitignore, project.clj, resources/public/index.html, src/main/clojure/clara/macros.clj, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/dsl.clj, src/main/clojure/clara/rules/schema.clj, src/test/clojure/clara/test_rules.clj, src/test/clojurescript/clara/test_rules_data.clj
This address the issue from https://github.com/rbrush/clara-rules/issues/178.
I didn't deal with issues of locals shadowing in LHS rule conditions right now.  They are theoretically possible, but probably much less common due to the fact that I'd not expect it to be "good practice" to do things like let-bindings in the constraints of LHS conditions.  We can address this later if needed, but qualified symbols do have some value in our static, "semantic" analysis done on LHS conditions within the Clara compiler.
If anyone is generated rules without using the clara.rules.dsl (we have cases) then the contract has not changed.  The generated rule RHS would have had to use "manually" qualified vars before and still will now.  The only addition is that the generated rules could also choose to …
=> No auto qualifying vars in rule RHS

project.clj
The figwheel support added in https://github.com/rbrush/clara-rules/commit/3f74817e736687fad33f37dd6f646d4e4b2a5d96 are being included in the clara-rules jar.  They shouldn't be since they are only useful during dev time.
I missed this previously.  The quick fix for this right now is to just use `:resource-paths []` since we do not have any real resources that need included in the jar for now.  In the future if we do, we can use a different resource path - I'd imagine it would be "src/main/resources" to follow the rest the directory structure pattern we are using.  We could also move the figwheel stuff where it is excluded if the "resources" path is still included.
=> Do not include dev (figwheel) resources built jar

src/main/clojure/clara/rules/engine.cljc
In clara.rules.engine the LocalTransport implementation of the `retract-elements` and `retract-tokens` has the potential to waste quite a bit of time.  In the reverse direction, the `send-elements` and `send-tokens` the issue is not present.  It looks like it was optimized a long while back with https://github.com/rbrush/clara-rules/commit/12f0cdb40437ca8b7bc3e1a23fe2d77d506d9287#diff-fc240c836498f0d897381182d11d3df8L88.  This optimization was beneficial for batch propagation to nodes with no join bindings.  It was also an optimization to create smaller map keys when doing a `group-by` (or our tuned variety).
Since `retract-elements` and `retract-tokens` are essentially the same implementation, I'll just refer to `retract-elements` from here on.
`retract-elements` always performs …
=> Optimize LocalTransport retraction

project.clj, src/test/clojurescript/clara/test.cljs
It looks like [1] changed the "simple" build for the ClojureScript tests and moved the file that this build depends on. [2] The build is now failing [3] when [4] fails to resolve the JavaScript variable clara.test.run [5].
This PR adds back the original simple build and moves the Figwheel build into a new ClojureScript build.  It also adds the source directory "src/test/common" to the advanced build source paths
to be the same as the simple build.  Lastly, if my understanding of the way ClojureScript
namespace forms is correct (which it might not be) it looks like [6] is relying on 
its transitive dependencies to require the ClojureScript version of cljs.test 
(as opposed to the .cljc version with macros). I went ahead and added an explicit require for the
cljs.test namespace there. …
=> Fix ClojureScript test build for whitespace optimizations

src/main/clojure/clara/rules.cljc, src/main/clojure/clara/rules/accumulators.cljc, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/rules/listener.cljc, src/main/clojure/clara/rules/memory.cljc, src/main/clojure/clara/tools/tracing.clj, src/test/clojure/clara/test_accumulators.clj, src/test/clojure/clara/test_durability.clj, src/test/clojure/clara/test_rules.clj, src/test/clojure/clara/tools/test_tracing.clj
- Addresses the issues 188, 189, and 200 for AccumulateNode
- When given, :retract-fn is used though
- Default :retract-fn is built into the node
- More performant than an external "retraction wrapper impl"
- :initial-value propagation semantics have been corrected (issue 188 and 189)
- :initial-value only added to memory once per all tokens in AccumulateNode left-activate
- :combine-fn is now optional and not provided by default for clara.rules.accumulators/reduce-to-accum
- Removed :combine-fn from built-in accumulators where it is not useful
- Test for retracting un-inserted fact in accumulate node (issue 200)
- Added tracing support to mem/remove-accum-reduced!
=> AccumulateNode no longer requires :combine-fn or :retract-fn

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/rules/platform.cljc, src/test/clojure/clara/test_rules.clj
Clara currently uses `clara.rules.platform/tuned-group-by` in a number of places.  The grouping that this function does is unordered and often can vary from one JVM to the next.  In particular I've noticed this happening in the `clara.rules.engine/flush-updates` which was causing non-deterministic insertion order to happen across rules.  This makes it harder for us to track bad performance cases since they keep fluctuating as we run in different processes.
A side-effect of `flush-updates` not behaving deterministically was that insertion order across rules of the same salience group level were not deterministic and didn't necessarily respect rule load order as was implemented in https://github.com/rbrush/clara-rules/issues/192.  From my preliminary testing of this, I see a slight …
=> Making rule engine execution order more deterministic

project.clj, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/durability_rules.clj, src/test/clojure/clara/test_durability.clj
This is a first pass at the work described in #198 .
There are two protocols in `clara.rules.durability`
* ISessionSerializer
* Responsible for serializing and deserializing the session (and rulebase) structure of the rule sessions
* This one will likely rarely, if ever, need to be customized by a consumer.  It has to be tightly coupled to the implementation of a rule session memory, which should generally be advised against
* Clara is going to provide a default implementation via Fressian in `clara.rules.durability.fressian` namespace
* This namespace requires a dependency on `org.clojure/data.fressian` see https://github.com/clojure/data.fressian
* This is an "optional" dependency and not included in Clara's explicit dependencies (it's only a `:dev` dependency for testing).
* …
=> Revised durability

src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/rules/listener.cljc, src/main/clojure/clara/tools/tracing.clj, src/test/clojure/clara/tools/test_tracing.clj
Added a listening capability to alpha-activate and alpha-retract, so that we can listen to the facts added or retracted the alpha network. We need it internally to know which facts that were inserted or retracted, matched some of the alpha nodes.
Listener on insert-facts and retract-facts will not give me facts that are guaranteed to match something in the alpha network.
I am not appending the trace for alpha-activate and alpha-retract in tracing listener, as it will add redundant information from insert-facts and retract-facts.
=> Added listening capability to alpha-activate and alpha-retract in alpha network

src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/test_rules.clj
The following throws an exception
```clj
(let [checked-all (assoc (acc/all)
;; Add an explicit :convert-return-fn to be sure that this
;; is only called with a valid reduced value.
:convert-return-fn
(fn [x]
(if (coll? x)
x
(is false
(str "An invalid value was given to the :convert-return-fn: " x)))))
q (dsl/parse-query [] [[Cold]
[?hs <- checked-all :from [Hot]]])
hot (->Hot 50)]
(is (empty? (-> (mk-session [q] :cache false)
(insert hot)
(retract hot)
fire-rules
(query q)
set))))
```
It should pass.
This was introduced in https://github.com/rbrush/clara-rules/commit/127a28314f067860e7a3748130b6318aca283d73 .
I made an optimization here that if an AccumulateNode had `right-activate`s, but no `left-activate` that the reduced value would not be calculated until later when/if a …
=> AccumulateNode right-retract with previous right-activate may fail

src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/tools/test_tracing.clj
I've found tracing to be quite useful, even with a limited subset of nodes making the listener calls.  I've ended up adding tracing calls in my local branch before to solve this.  Note that since the node is available to the listener calls, either the listener or processing on data collected by the listener can filter on the things that are relevant to a particular use-case.  I think there is some future work to be done here in tracing; for example, I'd like to have a helper function that gets only the tracing for descendants of alpha nodes for a particular type.  The first step is to have all the information available though.  This could break any listeners that depend on only a subset of nodes having tracing, but I think the correct way to do that sort of logic is for the listener to …
=> Add listener calls to all nodes

src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/test/clojure/clara/test_durability.clj, src/test/clojure/clara/test_fressian.clj
The sorted collections Fressian SerDe handlers didn't preserve metadata upon deserialization.  This means a deserialized sorted collection could potentially fail if it were re-serialized again afterwards.  This only applies to sorted collections that have a custom sort comparator fn, which must have its name specified in the metadata under the key `:clara.rules.durability/comparator-name`.
I added the start of some explicit testing of the behavior of the Fressian handlers in `clara.test-fressian` to try to be sure to catch more issues like this in the future.
I also added a test in `clara.test-durability` demonstrating the use-case that triggered this issue from the Serialize+Deserialize+Re-serialize a rulebase perspective.
`clara.rules.durability/assemble-restored-session` had a 2-arity …
=> Sorted coll Fressian handler fixes

src/main/clojure/clara/rules.cljc
This is just a straightforward typo fix for the docstring of clara.rules/mk-session.
=> Fix typo in documentation of fact-type-fn option

CONTRIBUTORS.md, src/main/clojure/clara/rules/compiler.clj, src/test/clojure/clara/test_rules.clj
Preserving metadata from the condition on the alpha expression doesn't seem to have much benefit and can lead to some rather odd exceptions if it contains unresolvable symbols, eg. 
the tested add, prior to the removal of the metadata, throws
```
ERROR in (test-unresolvable-symbols-in-metadata-on-conditions) (core.clj:4593)
Uncaught exception, not in assertion.
expected: nil
actual: clojure.lang.ExceptionInfo: Failed compiling alpha node
{:expr (clojure.core/fn [?__fact__ {:keys [rule-output]}] (clojure.core/let [this ?__fact__ temperature (.-temperature ?__fact__) ?__bindings__ (clojure.core/atom {})] (if (clojure.core/< temperature 20) (clojure.core/deref ?__bindings__) nil))), :condition {:type clara.rules.testfacts.Temperature, :constraints [(clojure.core/< temperature 20)]}, :env …
```
=> Remove metadata before trying to compile alpha nodes

CONTRIBUTORS.md, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/main/clojure/clara/rules/platform.cljc, src/test/clojure/clara/test_fressian.clj
The use of the dyanamic vars in clara.rules.durability and clara.rules.durability.fressian namsespace are wasting unnecessary cpu cycles. A ThreadLocal does a subset of the work done by a Clojure dynamic var and we do not really need any of the more sophisticated properties of dynamic vars for our purposes here. The proposal is to change these to ThreadLocal.
With this change we could see the performance gain, please look at the below test result.
```
> (defrecord MyRecord1 [n]) 
> (defrecord MyRecord2 [n]) 
> (defrecord MyRecord3 [n]) 
> (defrecord MyRecord4 [n]) 
> (defrecord MyRecord5 [n]) 
> (def records (into [] 
cat 
(for [n (range 1e6)] 
[(MyRecord1. n) (MyRecord2. n) (MyRecord3. n) (MyRecord4. n) (MyRecord5. n)]))) 
> (time (do (serde records) nil)) 
BEFORE: "Elapsed time: …
```
=> Clara durability should prefer ThreadLocal to dynamic vars

.gitignore, src/test/clojure/clara/test_rules.clj
Basically this test was passing because it was throwing an arity exception, not because of what it was testing.
Interestingly, cursive found this for me, which was neat.
=> Fix malformed test and add intellij files to .gitignore

src/main/clojure/clara/macros.clj, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/test_rules.clj
Fix for #267, ensuring a bound variable later used in a join binding is properly visible there. 
A side note: my editor cleaned up some extraneous whitespace when making this change, which normally I'd strip out and do in another commit. But I don't think it's terribly distracting and we should clean it up anyway, so I've left the whitespace cleanup in this commit as well.
=> Issue #267: local bindings not visible if used in a non-hash join.

src/main/clojure/clara/rules/memory.cljc, src/test/clojure/clara/tools/test_inspect.clj
- In clara.tools.inspect, return empty collections of matches when no match is present for a rule, query, or condition.
In some cases we previously returned a collection with elements that were either nil or an explanation record with nothing in it.
- Fix memory leak where bindings from facts that are retracted were held by the memory.
=> Issue 280:

src/main/clojure/clara/rules.cljc, src/test/clojurescript/clara/test.cljs, src/test/clojurescript/clara/test_salience.cljs
Copied salience test from `test-rules.clj` and modified for CLJS. Addresses #285 regarding whether salience and activation groups work in CLJS as they do in CLJ.
=> Add salience test CLJS

src/test/clojurescript/clara/test.cljs, src/test/js/runner.js
I added a commit on top of this in a branch in my fork that deliberately causes a ClojureScript-only failure.  The commit and the failed Travis CI build (I set up Travis to build my fork's branches) are visible in [that branch's history](https://github.com/WilliamParker/clara-rules/commits/issue186-cause-failure).
=> Issue 186: Make the Leiningen build fail when ClojureScript tests fail

CHANGELOG.md, CONTRIBUTORS.md, src/main/clojure/clara/tools/inspect.clj, src/test/clojure/clara/tools/test_inspect.clj
Previously, when iterating over a list of matches, each match
was assumed to be a vector of `[fact condition]` but was actually
a map of `{:fact ... :condition ...}`. Destructuring the map into
a vector threw an UnsupportedOperationException.
=> Fix exception in explain-activation

src/main/clojure/clara/rules/dsl.clj, src/test/clojure/clara/test_rules.clj, src/test/common/clara/test_dsl.cljc
- Previously an empty test condition (aka [:test]) was valid to the
parse and would generate pointless beta nodes. This change throws an
exception when parsing that.
This is something we noticed when doing an internal code review for something else and it seemed like an easy enough fix. I can't think of a situation in which we would want an empty test condition. Additionally, it looks like the parser would have intercepted it had`[:test]` been intended as a type anyway, so i dont think this changes anything functionally there.
=> Add constraint to parser for empty :test conditions

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/test_rules.clj
This is a draft of changes to fix https://github.com/cerner/clara-rules/issues/304.  We'll want to uplift these tests to be cross-platform using def-rules-test eventually, but since the relevant tests haven't been uplifted yet I just added a case to the existing test body in test-rules.
I'd like to think on this a bit more and make sure I haven't missed anything before merging but I wanted to go ahead and make this visible to anyone interested.
=> Issue 304: Respect binding groups in complex extracted negations

src/test/clojure/clara/test_rules.clj, src/test/clojurescript/clara/test.cljs, src/test/common/clara/test_rhs_retract.cljc
I realize this isn't a long new test file, but RHS(right-hand-side) retraction is a very logically distinctive operation and we will likely want to have additional tests of RHS retraction in the future, so I think it makes sense to add a separate test namespace for it.  Like similar PRs, this also has the benefit of testing both Clojure and ClojureScript while our existing tests that this ports test only Clojure.
Given that this is such a small change and a test-only one I plan to merge this tomorrow unless there are objections.
=> Refactor tests of RHS retraction to be cross-platform(clj/cljs)

src/test/clojure/clara/test_rules.clj, src/test/clojurescript/clara/test.cljs, src/test/common/clara/test_bindings.cljc, src/test/common/clara/test_dsl.cljc
This PR moves tests focused on the creation of binding variables and their use in joins from test-rules into their own cross-platform test file.
- test-join-with-fact-binding and test-join-on-fact-binding appear to be duplicates of each other; I kept test-join-with-fact-binding and deleted test-join-on-fact-binding without moving it into the new file.
- I moved test-local-scope-visible-in-join-filter from test-dsl to test-bindings; it seemed to fit better in this new namespace.  This is a test of the fix for https://github.com/cerner/clara-rules/issues/267.
=> Refactor tests for variable binding to be cross-platform

CHANGELOG.md, CONTRIBUTORS.md, src/main/clojure/clara/rules/dsl.clj
When using Clojure 1.9 and Clara Rules 0.18.0, requiring `clara.rules.dsl` or any namespace that requires it results in the following warning:
WARNING: qualified-keyword? already refers to: #'clojure.core/qualified-keyword? in namespace: clara.rules.dsl, being replaced by: #'clara.rules.dsl/qualified-keyword?
This change removes the inclusion of Clojure 1.9’s `qualified-keyword?` from this namespace, and thus the warning.
=> Don't override Clojure 1.9's `qualified-keyword?`

CHANGELOG.md, project.clj, src/main/clojure/clara/macros.clj, src/main/clojure/clara/rules.cljc, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/rules/schema.cljc, src/test/clojure/clara/long_running_tests.clj, src/test/clojure/clara/performance/test_compilation.clj, src/test/clojure/clara/test_rules.clj
I have changed both the Durability and Compiler evaluation of functions that are embedded in the rulebase, as part of this I also gave AlphaNodes an Id. 
I have also added some performance tests that generate a simple rulebase and compile, serialize and deserialize the rulebase. Running performance locally (`lein test :performance` )
gave me a before of:
```
Running Performance tests for:
Generated Session Compilation
==========================================
Mean: 13412.32ms
Standard Deviation : 5924.659171429188ms
Running Performance tests for:
Generated Session serialization
==========================================
Mean: 205.94ms
Standard Deviation : 85.99474635115799ms
Running Performance tests for:
Generated Session deserialization
==========================================
Mean: …
```
=> Issue #381 Reduce the number of Eval calls

CONTRIBUTORS.md, src/main/clojure/clara/rules/engine.cljc
Its not obvious `retract-fn` is part of accumulator. Adding it make it more explicit.
=> Add retract-fn to accumulator

CHANGELOG.md, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/test/clojure/clara/test_fressian.clj
I think this is the easiest solution for #419.
Comparing the Heap dumps provided on the original issue, the heap dumps now look like:
Pre-Serialization:
Post-Serialization:
While I would like to see the after heap usage closer to that of the before, i believe that Will's [comment](https://github.com/cerner/clara-rules/issues/419#issuecomment-460848471) explains why this is unlikely possible.
Running the Compilation/Serialization performance tests:
Before:
After:
Another thing to note is that prior to these changes the Session took up ~137MB on disk and after it was ~62.4MB. (This metric applies to the Heap dumps above, not the performance tests.)
@WilliamParker  @mrrodriguez
=> #419: [Durability] Increased memory usage post Serde.

CHANGELOG.md, src/main/clojure/clara/rules.cljc, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/schema.cljc, src/main/clojure/clara/tools/testing_utils.cljc, src/test/clojure/clara/test_durability.clj, src/test/clojure/clara/test_rules.clj
Using #420 's results as a baseline, meaning that these numbers include those changes as well, and using the same session. I was able to get a few heap dumps of the session without the `:compile-ctx` being stored.
Pre-serialization:
Post-serialization:
The thing to note here is that the pre-serialization, from my knowledge the standard use-case of clara, has dropped from ~523.6MB to ~504.0MB (again this is a Session containing 31k rules, so milage may vary).
The disk size of the Session also dropped from 62.4MB to 59.1MB.
=> #422: Expose flag to retain compile-ctx instead of maintaining it

CHANGELOG.md, src/main/clojure/clara/rules/compiler.clj, src/test/common/clara/test_simple_rules.cljc
For #433, i think this is the most straight forward approach. 
cc. @WilliamParker  @mrrodriguez
=> ISSUE-433: Behavior of rules sharing conditions within :or is incorrect

src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc
A quick addition for #237 
@mrrodriguez  @WilliamParker
=> Issue237: Add type to AlphaNodes for introspection

CHANGELOG.md, CONTRIBUTORS.md, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc, src/main/clojure/clara/tools/testing_utils.cljc, src/test/clojure/clara/test_compiler.clj, src/test/clojure/clara/test_durability.clj, src/test/clojure/clara/test_rules.clj
ensure we throw a more detailed condition exception when an exception is encountered during the evaluation of a TestNode expression
Closes #472
=> feat: throw condition exception on TestNode exception

.travis.yml, project.clj
=> feat: automate clojars releases for release tags with travis-ci

.travis.yml
I refactored the travis build config to use jobs with stages, it now has two stages:
1. test (runs the test commands)
2. deploy (only runs if on a release tag)
I also fixed the invalid syntax I setup previously used for filtering tags, and verified this one worked through testing on a separate repo (trial and error until I found what worked correctly).
Fixes Issue #473
=> Configure Travis CI build using stages

.clj-kondo/config.edn, .github/workflows/clojure.yml, .gitignore, CHANGELOG.md, README.md, clj-kondo/clj-kondo.exports/clara/rules/config.edn, clj-kondo/clj-kondo.exports/clara/rules/hooks/clara_rules.clj, project.clj, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/durability.clj, src/main/clojure/clara/rules/durability/fressian.clj, src/test/clojure/clara/test_rules.clj, src/test/clojurescript/clara/test_complex_negation.cljs, src/test/common/clara/test_common.cljc
I've implemented a clj-kondo hook to lint clara rules, this makes it easier to detect problems during development as well as add clojure-lsp based support for clara rules very easily.
details are briefly discussed in a clj-kondo issue: https://github.com/clj-kondo/clj-kondo/issues/2059
=> add clj-kondo support

CHANGELOG.md, src/main/clojure/clara/macros.clj, src/main/clojure/clara/rules/compiler.clj, src/main/clojure/clara/rules/engine.cljc, src/test/clojure/clara/test_rules.clj
- separates compile-test-handler from compile-test, this separates this functionality similar to how it was prior to compile-test being changed into it's current form and helps with advanced profiling techniques using alter-var-root to instrument compiled nodes.
- add env support to compile-test which was noted as something to fix in the future and was fairly simple to add
=> separate compile-test-handler from test-handler and add env
